# Generated by Django 4.2 on 2023-06-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_streamplatform_movie_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamplatform',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
