# Generated by Django 4.2 on 2023-06-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0006_review_writer_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='vote_ratio',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
