# Generated by Django 4.2 on 2023-06-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0007_movie_vote_ratio_movie_vote_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
